language: go
go:
        - 1.7
        - tip
go_import_path: github.com/zahlz/caddyslack
install:
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
        - go get github.com/stretchr/testify/assert
        - go get
test:
        - go vet ./...
        - go test -v ./... -v -covermode=count -coverprofile=coverage.out
script:
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
